# Generated by Django 5.2.5 on 2025-08-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_facilityimage_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='has_images',
            field=models.BooleanField(default=False, help_text='크롤링 가능하고 이미지가 있으면 True', verbose_name='이미지 존재 여부'),
        ),
    ]
