# Generated by Django 5.2.5 on 2025-08-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_facility_has_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='AI 요약 내용')),
                ('model_name', models.CharField(default='llama3.2', max_length=100, verbose_name='사용된 모델')),
                ('is_generated', models.BooleanField(default=False, verbose_name='요약 생성 완료')),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.facility')),
            ],
            options={
                'verbose_name': '시설 요약',
                'verbose_name_plural': '시설 요약',
            },
        ),
    ]
