# Generated by Django 5.2.5 on 2025-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_facilitysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='sido',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='시도'),
        ),
        migrations.AddField(
            model_name='facility',
            name='sigungu',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='시군구'),
        ),
    ]
