# Generated by Django 5.2.5 on 2025-08-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_evaluation_info_facility_homepage_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='summary',
            field=models.TextField(blank=True, help_text='AI가 생성한 시설 요약 내용', verbose_name='AI 요약'),
        ),
        migrations.DeleteModel(
            name='FacilitySummary',
        ),
    ]
