# Generated by Django 5.2.5 on 2025-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_facility_summary_delete_facilitysummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='code',
            field=models.CharField(help_text='고유한 시설 식별 코드', max_length=32, unique=True, verbose_name='시설 코드'),
        ),
    ]
