# Generated by Django 5.2.5 on 2025-08-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_facility_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='블로그 제목')),
                ('link', models.URLField(verbose_name='블로그 링크')),
                ('description', models.TextField(blank=True, verbose_name='블로그 설명')),
                ('bloggername', models.CharField(blank=True, max_length=100, verbose_name='블로거명')),
                ('bloggerlink', models.URLField(blank=True, verbose_name='블로거 링크')),
                ('postdate', models.CharField(blank=True, max_length=20, verbose_name='작성일')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='core.facility')),
            ],
            options={
                'verbose_name': '블로그',
                'verbose_name_plural': '블로그',
                'ordering': ['-postdate', '-created_at'],
                'unique_together': {('facility', 'link')},
            },
        ),
    ]
