# Generated by Django 5.2.5 on 2025-08-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='고유한 병원 식별 코드', max_length=32, unique=True, verbose_name='병원 코드')),
                ('name', models.CharField(max_length=255, verbose_name='병원명')),
                ('grade', models.CharField(blank=True, max_length=16, verbose_name='등급')),
                ('establishment_type', models.CharField(blank=True, max_length=32, verbose_name='설립구분')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name='설립일자')),
                ('bed_count', models.JSONField(default=dict, help_text='{"병상유형": 병상수} 형태', verbose_name='병상 수')),
                ('operation_facility', models.JSONField(default=dict, help_text='{"항목": "내용"} 형태', verbose_name='운영/시설')),
                ('doctor_count', models.JSONField(default=dict, help_text='{"과목": 의사수} 형태', verbose_name='의사수')),
                ('specialist_by_department', models.JSONField(default=dict, help_text='{"과목명": 전문의수} 형태', verbose_name='전문과목별(전문의수)')),
                ('department_specialists', models.JSONField(default=dict, help_text='{"진료과목": 전문의수} 형태', verbose_name='진료과목별(전문의수)')),
                ('other_staff', models.JSONField(default=dict, help_text='{"직종": 인원수} 형태', verbose_name='기타인력')),
                ('consultation_hours', models.JSONField(default=dict, help_text='{"요일/시간": "내용"} 형태', verbose_name='진료시간')),
                ('medical_fee_info', models.JSONField(default=dict, help_text='{"항목": "금액"} 형태', verbose_name='진료비정보')),
                ('has_images', models.BooleanField(default=False, help_text='크롤링 가능하고 이미지가 있으면 True', verbose_name='이미지 존재 여부')),
                ('sido', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='시도')),
                ('sigungu', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='시군구')),
                ('homepage_url', models.URLField(blank=True, verbose_name='홈페이지 URL')),
                ('summary', models.TextField(blank=True, help_text='AI가 생성한 병원 요약 내용', verbose_name='AI 요약')),
            ],
            options={
                'verbose_name': '요양병원',
                'verbose_name_plural': '요양병원',
                'ordering': ['name'],
            },
        ),
    ]
