# Generated by Django 5.2.5 on 2025-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.CharField(blank=True, help_text='병원 주소 및 위치 정보', max_length=512, verbose_name='위치정보'),
        ),
    ]
