# Generated by Django 5.2.5 on 2025-08-23 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_hospital_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='core.tag', verbose_name='태그'),
        ),
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='hospital_images/%Y/%m/%d')),
                ('original_url', models.URLField(max_length=500, unique=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.hospital')),
            ],
            options={
                'verbose_name': '병원 이미지',
                'verbose_name_plural': '병원 이미지',
                'ordering': ['-created_at'],
            },
        ),
    ]
