# Generated by Django 5.2.5 on 2025-08-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_facility_evaluation_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='code',
            field=models.CharField(help_text='고유한 병원 식별 코드', max_length=100, unique=True, verbose_name='병원 코드'),
        ),
    ]
