# Generated by Django 5.2.5 on 2025-09-06 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_hospital_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityevaluation',
            options={'verbose_name': '��가정보', 'verbose_name_plural': '평가정보'},
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='tags',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='cards',
            field=models.JSONField(blank=True, default=list, help_text='RAG 검색 결과 카드 데이터', verbose_name='카드 정보'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='RAG 검색 소스 데이터', verbose_name='소스 정보'),
        ),
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='위도 (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='location',
            field=models.CharField(blank=True, help_text='시설 전체 주소(도로명/지번 포함)', max_length=512, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='경도 (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='위도 (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='경도 (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.hospital'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='첫 질문 요약 등을 제목으로 사용', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession'),
        ),
    ]
