# Generated by Django 5.2.5 on 2025-09-08 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_facilityevaluation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 시 True (소프트 삭제)')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.facility')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.hospital')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['facility', 'created_at'], name='core_commen_facilit_c6abc1_idx'), models.Index(fields=['hospital', 'created_at'], name='core_commen_hospita_20e790_idx'), models.Index(fields=['parent'], name='core_commen_parent__e30d40_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('facility__isnull', False), ('hospital__isnull', True)), models.Q(('facility__isnull', True), ('hospital__isnull', False)), _connector='OR'), name='comment_one_target_only')],
            },
        ),
    ]
