# Generated by Django 5.2.5 on 2025-08-24 16:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='summary_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='summary_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
