# Generated by Django 5.2.5 on 2025-08-24 16:09

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_facility_summary_embedding_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facility',
            index=pgvector.django.indexes.HnswIndex(fields=['summary_embedding'], name='facility_sum_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=pgvector.django.indexes.HnswIndex(fields=['summary_embedding'], name='hospital_sum_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
