# Generated by Django 5.2.5 on 2025-09-08 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1~5 사이 평점 (최상위 리뷰에만 사용)', null=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['rating'], name='core_commen_rating_89735a_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 1), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='comment_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False), ('is_deleted', False), ('parent__isnull', True)), fields=('user', 'facility'), name='uniq_user_facility_review'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', False), ('is_deleted', False), ('parent__isnull', True)), fields=('user', 'hospital'), name='uniq_user_hospital_review'),
        ),
    ]
