# Generated by Django 5.2.5 on 2025-08-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_facility_facility_sum_hnsw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.hospital'),
        ),
    ]
