# Generated by Django 5.2.5 on 2025-08-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_hospital_tags_tag_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='위도 (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='경도 (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='위도 (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='경도 (WGS84)', max_digits=9, null=True),
        ),
    ]
