# Generated by Django 5.2.5 on 2025-08-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_facility_latitude_facility_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityevaluation',
            options={'verbose_name': '��가정보', 'verbose_name_plural': '평가정보'},
        ),
        migrations.AddField(
            model_name='facility',
            name='location',
            field=models.CharField(blank=True, help_text='시설 전체 주소(도로명/지번 포함)', max_length=512, verbose_name='주소'),
        ),
    ]
