# Generated by Django 5.2.5 on 2025-09-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_chatsession_and_history_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='cards',
            field=models.JSONField(blank=True, default=list, help_text='RAG 검색 결과 카드 데이터', verbose_name='카드 정보'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='RAG 검색 소스 데이터', verbose_name='소스 정보'),
        ),
    ]
