# Generated by Django 5.2.5 on 2025-09-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_chathistory_cards_chathistory_sources'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='facility',
            name='facility_sum_hnsw',
        ),
        migrations.RemoveIndex(
            model_name='hospital',
            name='hospital_sum_hnsw',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='summary_embedding',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='summary_embedding',
        ),
    ]
